// Fiches explicatives des nutriments (adultes). Rédigées à partir des documents publics de l'Anses, de l'EFSA et de l'OMS,
// en vulgarisation : à relire, ce n'est pas un avis médical. Les meilleures sources alimentaires sont calculées
// à partir de Ciqual, pas écrites ici.
//
// Champs : resume (une phrase), role, manque, exces, conseils, grossesse (facultatifs).
module.exports = {
  kcal: {
    resume: "L'énergie apportée par l'aliment, fournie par les glucides, les lipides, les protéines, les fibres et l'alcool.",
    role: "Elle fait fonctionner le corps au repos (cœur, cerveau, température, environ 60 à 70 % de la dépense), la digestion et l'activité physique. 1 g de lipides apporte 9 kcal, 1 g d'alcool 7 kcal, 1 g de protéines ou de glucides 4 kcal, 1 g de fibres 2 kcal.",
    manque: "Un apport durablement insuffisant fait perdre du poids, y compris du muscle, et entraîne fatigue, frilosité, baisse de l'immunité et, chez la femme, troubles du cycle. Les carences en vitamines et minéraux deviennent plus probables.",
    exces: "Un excès régulier est stocké sous forme de graisse. Le surpoids, surtout abdominal, augmente le risque de diabète de type 2, d'hypertension, de maladies cardiovasculaires et de certains cancers.",
    conseils: "Le besoin varie beaucoup selon l'âge, la taille et l'activité : le repère de l'appli n'est qu'un ordre de grandeur, à régler dans le profil. La densité nutritionnelle compte plus que les calories seules : préférer les aliments qui apportent beaucoup de vitamines et minéraux pour peu de calories.",
    grossesse: "Les besoins augmentent peu : environ +70 kcal au 1er trimestre, +260 kcal au 2e et +500 kcal au 3e (EFSA). Il ne s'agit pas de « manger pour deux ».",
  },
  eau: {
    resume: "Le corps est composé à 60 % d'eau, renouvelée chaque jour par les boissons et les aliments.",
    role: "Elle transporte les nutriments, régule la température (transpiration), élimine les déchets par les reins et lubrifie articulations et muqueuses.",
    manque: "La déshydratation se manifeste par la soif, la fatigue, les maux de tête, la baisse de concentration, la constipation et des urines foncées. Une perte de 2 % du poids en eau réduit déjà les performances physiques et intellectuelles.",
    exces: "Rare chez une personne en bonne santé : les reins éliminent le surplus. Boire plusieurs litres en très peu de temps peut provoquer une hyponatrémie (sodium trop dilué dans le sang), dangereuse.",
    conseils: "Le repère inclut l'eau des aliments (environ 20 à 30 % de l'apport) : il reste en pratique 1,5 L environ à boire, davantage par forte chaleur ou en cas d'effort. Fruits, légumes, soupes et laitages sont riches en eau.",
    grossesse: "Le besoin augmente d'environ 300 mL par jour.",
  },
  prot: {
    resume: "Les briques du corps : muscles, organes, peau, enzymes, hormones et anticorps sont faits de protéines.",
    role: "Elles construisent et renouvellent les tissus, transportent des molécules (hémoglobine), défendent l'organisme (anticorps) et accélèrent les réactions chimiques (enzymes). Elles sont formées de 20 acides aminés, dont 9 « indispensables » que le corps ne sait pas fabriquer.",
    manque: "Fonte musculaire, fatigue, cicatrisation lente, infections plus fréquentes, perte de cheveux, œdèmes dans les cas sévères. Les personnes âgées, les régimes très restrictifs et les convalescents sont les plus exposés.",
    exces: "Chez l'adulte en bonne santé, jusqu'à environ 2 g par kg et par jour ne pose pas de problème démontré. Au-delà, ou en cas de maladie rénale, la charge pour les reins augmente. Un excès de viande rouge et de charcuterie est par ailleurs associé à un risque accru de cancer colorectal.",
    conseils: "Le repère (0,83 g par kg de poids) est calculé à partir du poids du profil. Varier les sources : œufs, poissons, volailles, laitages, légumineuses, céréales complètes, oléagineux. Associer céréales et légumineuses (riz et lentilles, semoule et pois chiches) donne des protéines végétales complètes.",
    grossesse: "Les besoins augmentent surtout aux 2e et 3e trimestres (environ +9 puis +28 g par jour selon l'EFSA).",
  },
  gluc: {
    resume: "Le carburant principal du corps et le seul du cerveau dans les conditions normales : sucres et amidon.",
    role: "Digérés en glucose, ils fournissent une énergie rapide aux muscles et au cerveau (environ 130 g de glucose par jour pour le cerveau). Le surplus est stocké sous forme de glycogène dans le foie et les muscles.",
    manque: "Un apport très bas (régime cétogène) peut provoquer fatigue, maux de tête, baisse des performances sportives, constipation (moins de fibres) et mauvaise haleine au début.",
    exces: "Ce n'est pas tant la quantité que la qualité qui pose problème : beaucoup de glucides raffinés et de sucres font monter vite la glycémie, favorisent la prise de poids, le diabète de type 2 et les caries.",
    conseils: "Repère : 40 à 55 % des calories. Préférer les glucides complexes riches en fibres (céréales complètes, légumineuses, légumes, fruits entiers) aux produits raffinés et sucrés.",
  },
  sucres: {
    resume: "Les glucides simples, au goût sucré : ceux naturellement présents (fruits, lait) et ceux ajoutés.",
    role: "Source d'énergie immédiate. Ceux des fruits entiers et du lait arrivent avec des fibres, des vitamines ou des protéines ; les sucres ajoutés n'apportent que des calories.",
    manque: "Pas de besoin propre en sucres : le corps fabrique son glucose à partir de l'amidon ou d'autres nutriments.",
    exces: "Caries, prise de poids, hausse des triglycérides, stéatose du foie (surtout avec le fructose des boissons sucrées), risque accru de diabète de type 2. Les boissons sucrées sont la source la plus problématique car elles ne rassasient pas.",
    conseils: "L'Anses fixe une limite de 100 g par jour de sucres totaux (hors lactose et galactose) ; l'OMS recommande moins de 10 % des calories en sucres libres (environ 50 g), idéalement moins de 5 %. Ici le repère porte sur les sucres totaux, lactose compris.",
  },
  amidon: {
    resume: "Le sucre « lent » des céréales, du pain, des pommes de terre et des légumineuses : de longues chaînes de glucose.",
    role: "Digéré progressivement en glucose, c'est la principale source d'énergie de l'alimentation. Une partie, l'amidon résistant (pâtes al dente, pommes de terre refroidies, légumineuses), se comporte comme une fibre et nourrit le microbiote.",
    exces: "Les amidons raffinés (pain blanc, purée, riz blanc très cuit) élèvent vite la glycémie. Mieux vaut les versions complètes et une cuisson pas trop longue.",
  },
  saccharose: { resume: "Le sucre de table (betterave, canne), formé de glucose et de fructose. Présent aussi dans les fruits. C'est le principal sucre ajouté des produits sucrés." },
  glucose: { resume: "Le sucre que le corps utilise directement et que mesure la glycémie. Présent dans les fruits, le miel et les sirops de glucose des produits industriels." },
  fructose: { resume: "Le sucre des fruits et du miel, aussi présent dans le saccharose et le sirop de glucose-fructose. En grande quantité, surtout dans les boissons sucrées, il favorise la graisse dans le foie et la hausse des triglycérides ; les fruits entiers ne posent pas ce problème." },
  lactose: { resume: "Le sucre du lait. Certaines personnes le digèrent mal (déficit en lactase) : ballonnements, diarrhée. Les fromages affinés en contiennent très peu et les yaourts le rendent plus digeste." },
  galactose: { resume: "Sucre issu de la digestion du lactose, présent en petite quantité dans les produits laitiers fermentés." },
  maltose: { resume: "Sucre formé de deux glucoses, issu de la dégradation de l'amidon (malt, céréales germées, sirops, bière)." },
  polyols: { resume: "Édulcorants de charge (sorbitol, xylitol, maltitol…) dans les produits « sans sucre » et certains fruits (pruneaux). Moins caloriques et sans effet sur les caries, mais laxatifs à forte dose (à partir de 10 à 20 g)." },
  acidesorg: { resume: "Acides naturels (citrique, malique, lactique, acétique…) des fruits, du vinaigre et des produits fermentés : ils donnent l'acidité et apportent un peu d'énergie (environ 3 kcal par gramme)." },
  fibres: {
    resume: "La partie des végétaux que l'intestin ne digère pas, mais que le microbiote fermente.",
    role: "Elles accélèrent le transit, augmentent la satiété, ralentissent l'absorption des sucres et du cholestérol, et nourrissent les bactéries intestinales qui produisent des acides gras protecteurs pour le côlon.",
    manque: "Constipation, satiété moindre. Une alimentation pauvre en fibres est associée à un risque plus élevé de cancer colorectal, de maladies cardiovasculaires et de diabète de type 2. En France, la plupart des adultes en mangent moins de 20 g par jour.",
    exces: "Une augmentation brutale donne des ballonnements et des gaz : augmenter progressivement et boire suffisamment. À très haute dose, les fibres peuvent gêner un peu l'absorption du fer, du zinc et du calcium.",
    conseils: "Repère : 30 g par jour. Légumineuses, céréales complètes, légumes, fruits (avec la peau), oléagineux et graines.",
  },
  alcool: {
    resume: "L'éthanol des boissons alcoolisées : 7 kcal par gramme, sans aucun intérêt nutritionnel.",
    role: "Aucun besoin. Le corps le traite comme un toxique et l'élimine en priorité par le foie.",
    exces: "Toxique pour le foie, le cerveau, le cœur et le pancréas. L'alcool est cancérogène dès le premier verre (bouche, gorge, œsophage, foie, sein, côlon). Il favorise aussi l'hypertension et la prise de poids.",
    conseils: "Repère de Santé publique France : pas plus de 10 verres standard par semaine, pas plus de 2 par jour et des jours sans alcool. Un verre standard contient 10 g d'alcool. Le repère de l'appli (20 g) correspond au maximum de 2 verres un jour donné.",
    grossesse: "Zéro alcool pendant toute la grossesse et l'allaitement : il traverse le placenta et peut provoquer des troubles du développement de l'enfant.",
  },
  lip: {
    resume: "Les graisses : réserve d'énergie, constituant des cellules et transporteur des vitamines A, D, E et K.",
    role: "Elles forment les membranes de toutes les cellules (le cerveau est composé à 60 % de lipides), servent à fabriquer des hormones, isolent du froid et permettent l'absorption des vitamines liposolubles. Leur qualité dépend des acides gras qui les composent.",
    manque: "Un apport trop bas (moins de 20 % des calories) expose à des manques en acides gras essentiels et en vitamines liposolubles, à une peau sèche et à des troubles hormonaux.",
    exces: "Très caloriques (9 kcal par gramme) : un excès favorise la prise de poids. Un excès d'acides gras saturés augmente le LDL-cholestérol.",
    conseils: "Repère : 35 à 40 % des calories. Privilégier les huiles de colza, de noix et d'olive, les poissons gras et les oléagineux ; limiter beurre, crème, fritures, charcuteries et viennoiseries.",
  },
  ags: {
    resume: "Les graisses solides à température ambiante : beurre, fromage, viandes grasses, huiles de palme et de coco.",
    role: "Source d'énergie et constituants des membranes. Le corps sait les fabriquer : il n'y a pas de besoin à couvrir par l'alimentation.",
    exces: "Les acides laurique, myristique et palmitique augmentent le LDL-cholestérol et le risque cardiovasculaire lorsqu'ils sont consommés en excès. L'effet dépend toutefois de l'aliment : les produits laitiers fermentés semblent plus neutres que la charcuterie.",
    conseils: "L'Anses fixe une limite de 12 % des calories (dont 8 % au plus pour les acides laurique, myristique et palmitique). Remplacer une partie des graisses saturées par des huiles végétales riches en insaturés est bénéfique.",
  },
  agmi: {
    resume: "Graisses dont la principale est l'acide oléique de l'huile d'olive, de l'avocat et des noisettes.",
    role: "Source d'énergie. Le corps les fabrique aussi ; elles ne sont pas indispensables mais remplacent avantageusement les graisses saturées.",
    exces: "Neutres pour le cholestérol. Comme toutes les graisses, elles restent caloriques.",
    conseils: "Repère indicatif de l'Anses : environ 15 à 20 % des calories.",
  },
  agpi: {
    resume: "Graisses fluides des huiles végétales, des noix, des graines et des poissons, dont les oméga-6 et oméga-3.",
    role: "Elles contiennent les deux acides gras essentiels que le corps ne sait pas fabriquer (acide linoléique, oméga-6, et acide alpha-linolénique, oméga-3), indispensables au cerveau, à la rétine et à la régulation de l'inflammation.",
    exces: "Très sensibles à l'oxydation : éviter de chauffer fortement les huiles riches en oméga-3 (colza, noix, lin). Le problème le plus courant est un déséquilibre (trop d'oméga-6, pas assez d'oméga-3).",
  },
  oleique: { resume: "Le principal acide gras mono-insaturé (oméga-9), majoritaire dans l'huile d'olive et l'huile de colza. Remplacer des graisses saturées par de l'acide oléique fait baisser le LDL-cholestérol." },
  linoleique: {
    resume: "Le principal oméga-6, acide gras essentiel : huiles de tournesol, de maïs, de pépins de raisin, noix, graines.",
    role: "Indispensable aux membranes cellulaires, à la peau et à la fabrication de messagers impliqués dans l'inflammation et la coagulation.",
    manque: "Rare : peau sèche et squameuse, cicatrisation lente.",
    exces: "En excès par rapport aux oméga-3, il peut gêner leur utilisation. L'Anses vise un rapport oméga-6 / oméga-3 inférieur à 5 ; il est souvent de 10 à 15 dans l'alimentation française.",
    conseils: "Repère : 4 % des calories. En pratique il est facilement couvert ; on gagne à remplacer l'huile de tournesol par l'huile de colza.",
  },
  ala: {
    resume: "L'oméga-3 végétal, acide gras essentiel : huiles de colza, de noix et de lin, noix, graines de lin et de chia.",
    role: "Le corps ne sait pas le fabriquer. Il en dérive (en petite quantité, moins de 10 %) l'EPA et le DHA. Il contribue à la santé cardiovasculaire.",
    manque: "Fréquent en France : la majorité des adultes n'atteint pas le repère. Un manque déséquilibre le rapport oméga-6 / oméga-3.",
    exces: "Pas d'effet indésirable connu aux apports alimentaires.",
    conseils: "Repère : 1 % des calories, soit environ 2 g par jour. Une cuillère à soupe d'huile de colza en apporte environ 1 g ; 6 cerneaux de noix environ 1,5 g.",
  },
  epa: {
    resume: "Oméga-3 à longue chaîne des poissons gras et des fruits de mer.",
    role: "Il module l'inflammation, fait baisser les triglycérides et contribue à la santé du cœur. Le corps en fabrique très peu à partir de l'oméga-3 végétal.",
    manque: "Associé à un risque cardiovasculaire plus élevé. Fréquent chez ceux qui mangent peu de poisson.",
    exces: "À fortes doses (compléments de plusieurs grammes), risque de saignement accru.",
    conseils: "Repère : 250 mg d'EPA et 250 mg de DHA par jour (Anses), soit environ deux portions de poisson par semaine dont un poisson gras (sardine, maquereau, hareng, saumon).",
  },
  dha: {
    resume: "Oméga-3 à longue chaîne, constituant majeur du cerveau et de la rétine. Poissons gras surtout.",
    role: "Indispensable au fonctionnement des neurones et de la vision ; protège le cœur.",
    manque: "Associé à un risque cardiovasculaire plus élevé et, chez le fœtus et le nourrisson, à un moins bon développement visuel et cérébral.",
    exces: "À fortes doses (compléments), risque de saignement accru.",
    conseils: "Repère : 250 mg par jour. Sardines, maquereau, hareng, saumon, anchois ; une portion de 100 g de sardines en apporte environ 1 g.",
    grossesse: "Repère porté à 500 mg par jour pendant la grossesse et l'allaitement. Choisir des petits poissons gras (sardine, maquereau, hareng) et éviter les gros prédateurs (espadon, thon rouge, requin) à cause du mercure.",
  },
  arachidonique: { resume: "Oméga-6 à longue chaîne présent dans les viandes, les abats et les œufs. Le corps le fabrique à partir de l'acide linoléique ; il sert de précurseur à des messagers de l'inflammation." },
  butyrique: { resume: "Acide gras saturé à chaîne courte typique du beurre. Le microbiote en fabrique aussi à partir des fibres : il nourrit les cellules du côlon." },
  caproique: { resume: "Acide gras saturé à chaîne courte des laits de chèvre et de vache." },
  caprylique: { resume: "Acide gras saturé à chaîne moyenne (lait de chèvre, huile de coco), vite utilisé comme énergie par le foie." },
  caprique: { resume: "Acide gras saturé à chaîne moyenne (lait de chèvre, huile de coco)." },
  laurique: { resume: "Acide gras saturé majoritaire dans l'huile de coco et de palmiste. Il fait monter le LDL-cholestérol en excès." },
  myristique: { resume: "Acide gras saturé des produits laitiers et de l'huile de coco. C'est le plus « athérogène » en excès." },
  palmitique: { resume: "L'acide gras saturé le plus répandu (huile de palme, viandes, produits laitiers). Il fait monter le LDL-cholestérol en excès." },
  stearique: { resume: "Acide gras saturé du chocolat (beurre de cacao) et des graisses animales. Contrairement aux autres saturés, il a peu d'effet sur le cholestérol." },
  cholesterol: {
    resume: "Une graisse fabriquée surtout par le foie ; l'alimentation n'en apporte qu'une petite partie (œufs, abats, crustacés, beurre).",
    role: "Constituant des membranes cellulaires, il sert à fabriquer la vitamine D, les hormones sexuelles, le cortisol et la bile.",
    exces: "Pour la plupart des gens, le cholestérol des aliments influe peu sur celui du sang : ce sont surtout les graisses saturées et la génétique qui comptent. Aucune limite n'est fixée par l'Anses ni l'EFSA ; une personne ayant un excès de LDL-cholestérol peut néanmoins avoir intérêt à modérer les aliments très riches.",
  },
  sel: {
    resume: "Le chlorure de sodium. 1 g de sel contient 0,4 g de sodium. Il vient surtout du pain, de la charcuterie, du fromage et des plats préparés.",
    role: "Il apporte le sodium et le chlorure nécessaires à l'équilibre de l'eau du corps, à la pression artérielle, aux nerfs et aux muscles. Le besoin réel est faible (1 à 2 g de sel par jour).",
    manque: "Exceptionnel avec une alimentation habituelle, sauf transpiration très abondante ou maladie (vomissements, diarrhées) : crampes, fatigue, maux de tête.",
    exces: "Le principal facteur alimentaire d'hypertension artérielle, donc d'AVC et d'infarctus. Il est aussi associé au cancer de l'estomac et à une perte de calcium dans les urines.",
    conseils: "L'OMS recommande moins de 5 g par jour ; les Français en mangent 8 à 9 g. Environ 75 % du sel vient des produits transformés : regarder les étiquettes, saler peu en cuisine, utiliser herbes et épices. Choisir du sel iodé.",
  },
  sodium: {
    resume: "Le minéral apporté surtout par le sel (1 g de sel = 400 mg de sodium).",
    role: "Il règle la quantité d'eau dans le corps et la pression artérielle, et permet la transmission nerveuse et la contraction musculaire.",
    manque: "Rare : maux de tête, nausées, crampes, confusion (hyponatrémie, surtout en cas de pertes importantes).",
    exces: "Hypertension artérielle et risque cardiovasculaire, surtout s'il est associé à peu de potassium.",
    conseils: "L'EFSA juge 2 g de sodium par jour sûrs et suffisants pour l'adulte (soit 5 g de sel). Manger plus de fruits et légumes, riches en potassium, compense en partie.",
  },
  calcium: {
    resume: "Le minéral le plus abondant du corps : 99 % se trouvent dans les os et les dents.",
    role: "Solidité des os et des dents, contraction musculaire (y compris le cœur), transmission nerveuse, coagulation du sang.",
    manque: "À long terme, perte de masse osseuse (ostéoporose) et fractures. Un manque aigu dans le sang (rare, d'origine hormonale) provoque crampes et fourmillements.",
    exces: "Au-delà de 2 500 mg par jour, surtout par des compléments : calculs rénaux, constipation, gêne à l'absorption du fer et du zinc.",
    conseils: "Repère : 950 mg par jour (1 000 mg avant 25 ans). Laitages, mais aussi eaux minérales calciques (jusqu'à 500 mg par litre), sardines avec arêtes, amandes, choux, tofu au calcium. La vitamine D est indispensable pour l'absorber.",
  },
  chlorure: {
    resume: "Minéral apporté presque entièrement par le sel.",
    role: "Il équilibre l'eau et l'acidité du corps avec le sodium et le potassium, et sert à fabriquer l'acide de l'estomac.",
    manque: "Rarissime en dehors de vomissements prolongés.",
    exces: "Suit l'excès de sel, dont il partage les effets.",
  },
  cuivre: {
    resume: "Oligo-élément présent dans les abats, les fruits de mer, le cacao, les oléagineux et les légumineuses.",
    role: "Nécessaire à l'utilisation du fer, à la formation du collagène, à la défense contre les radicaux libres et au fonctionnement du système nerveux et immunitaire.",
    manque: "Rare : anémie, baisse des globules blancs, troubles neurologiques. Peut survenir avec des compléments de zinc à forte dose.",
    exces: "Au-delà de 5 mg par jour (compléments, eau de canalisations en cuivre) : nausées, atteintes du foie.",
  },
  fer: {
    resume: "Le minéral qui transporte l'oxygène dans le sang (hémoglobine) et les muscles.",
    role: "Transport de l'oxygène, production d'énergie dans les cellules, immunité, développement du cerveau. Le fer « héminique » (viandes, poissons) est bien absorbé (environ 25 %) ; le fer végétal beaucoup moins (environ 5 %).",
    manque: "La carence la plus répandue au monde. Fatigue, essoufflement, pâleur, ongles cassants, chute de cheveux, baisse de l'immunité et de la concentration, puis anémie. Les femmes réglées, les femmes enceintes et les végétariens sont les plus exposés.",
    exces: "Rare par l'alimentation, sauf en cas d'hémochromatose (maladie génétique fréquente en Europe). Les compléments inutiles provoquent troubles digestifs et, en excès chronique, atteintes du foie et du cœur.",
    conseils: "Repère : 11 mg pour les hommes et les femmes ménopausées, 16 mg pour les femmes ayant des règles abondantes ; l'appli retient 16 mg pour une femme. Associer le fer végétal (lentilles, épinards, tofu) à de la vitamine C (agrumes, poivron, persil) ; éloigner thé et café des repas, car ils en freinent l'absorption.",
    grossesse: "Besoins accrus (repère de 16 mg) : le volume de sang augmente et le bébé constitue ses réserves. Un dosage sanguin permet de vérifier s'il faut un complément.",
  },
  iode: {
    resume: "Oligo-élément indispensable à la thyroïde : poissons, fruits de mer, algues, laitages, œufs et sel iodé.",
    role: "Il sert à fabriquer les hormones thyroïdiennes qui règlent le métabolisme, la température et la croissance, et qui sont décisives pour le développement du cerveau du fœtus.",
    manque: "Goitre (thyroïde qui grossit), hypothyroïdie (fatigue, frilosité, prise de poids). Pendant la grossesse, un manque peut altérer le développement intellectuel de l'enfant. Les apports sont limites dans une partie de la population française.",
    exces: "Au-delà de 600 µg par jour, surtout avec des algues séchées très riches ou des compléments : dérèglement de la thyroïde (hypo- ou hyperthyroïdie).",
    conseils: "Repère : 150 µg par jour. Utiliser du sel iodé (sans saler davantage), manger du poisson ou des fruits de mer, des laitages. Prudence avec les algues séchées (kombu notamment) dont la teneur est très élevée.",
    grossesse: "Repère porté à 200 µg par jour pendant la grossesse et l'allaitement.",
  },
  magnesium: {
    resume: "Minéral présent dans les céréales complètes, les légumineuses, les oléagineux, le chocolat noir et certaines eaux minérales.",
    role: "Il intervient dans plus de 300 réactions : production d'énergie, contraction et détente musculaire, transmission nerveuse, rythme cardiaque, solidité des os.",
    manque: "Fatigue, crampes, tremblements des paupières, irritabilité, troubles du rythme cardiaque dans les cas sévères. Les apports sont souvent un peu justes avec une alimentation raffinée.",
    exces: "Sans danger par l'alimentation (les reins éliminent le surplus). Les compléments au-delà de 250 mg par jour peuvent provoquer des diarrhées.",
    conseils: "Repère : 420 mg pour un homme, 360 mg pour une femme. Préférer les céréales complètes aux raffinées (qui perdent l'essentiel du magnésium), manger des légumineuses, des oléagineux, du chocolat noir ; certaines eaux en contiennent plus de 100 mg par litre.",
  },
  manganese: {
    resume: "Oligo-élément des céréales complètes, du thé, des oléagineux et des légumineuses.",
    role: "Il active des enzymes qui servent à la formation des os et du cartilage, au métabolisme des glucides et à la défense antioxydante.",
    manque: "Exceptionnel chez l'humain.",
    exces: "Toxique pour le système nerveux en cas d'exposition élevée, surtout par inhalation (milieu professionnel) ou par une eau très chargée ; rare par l'alimentation.",
  },
  phosphore: {
    resume: "Minéral associé au calcium dans les os ; présent dans presque tous les aliments riches en protéines.",
    role: "Constituant des os et des dents, de l'ADN, des membranes cellulaires et de l'ATP, la molécule qui stocke l'énergie.",
    manque: "Très rare : faiblesse musculaire, douleurs osseuses.",
    exces: "Les additifs phosphatés (charcuteries, fromages fondus, sodas au cola) font monter les apports. Un excès chronique est néfaste en cas de maladie rénale et pourrait fragiliser les os et les artères.",
  },
  potassium: {
    resume: "Le minéral des fruits et légumes, des légumineuses, des pommes de terre et des oléagineux.",
    role: "Avec le sodium, il règle l'eau des cellules, la transmission nerveuse et la contraction des muscles, dont le cœur. Il aide à faire baisser la tension.",
    manque: "Faiblesse, crampes, troubles du rythme cardiaque (surtout en cas de diurétiques ou de vomissements). Un apport faible et beaucoup de sel augmentent le risque d'hypertension et d'AVC.",
    exces: "Sans danger par l'alimentation chez une personne en bonne santé. Prudence en cas d'insuffisance rénale ou de certains médicaments (sels de régime au potassium compris).",
    conseils: "Repère : 3 500 mg par jour. Fruits et légumes à chaque repas, légumineuses, pommes de terre, fruits secs, oléagineux.",
  },
  selenium: {
    resume: "Oligo-élément des noix du Brésil, des poissons, des fruits de mer, des abats et des œufs.",
    role: "Il protège les cellules du stress oxydant, contribue au fonctionnement de la thyroïde, à l'immunité et à la fertilité.",
    manque: "Rare en France : fatigue, baisse de l'immunité, troubles de la thyroïde.",
    exces: "Au-delà d'environ 255 µg par jour : odeur d'ail de l'haleine, cheveux et ongles cassants, troubles digestifs et nerveux. Une seule noix du Brésil peut contenir 50 à 100 µg : 1 à 2 par jour suffisent.",
  },
  zinc: {
    resume: "Oligo-élément des viandes, des fruits de mer (huîtres surtout), des fromages, des céréales complètes et des légumineuses.",
    role: "Il participe à plus de 200 enzymes : immunité, cicatrisation, croissance, goût et odorat, peau et cheveux, fertilité.",
    manque: "Infections plus fréquentes, cicatrisation lente, perte du goût, chute de cheveux, problèmes de peau. Plus fréquent chez les végétariens, car les phytates des céréales complètes et des légumineuses freinent son absorption.",
    exces: "Au-delà de 25 mg par jour (compléments) : il gêne l'absorption du cuivre, ce qui peut provoquer anémie et troubles neurologiques ; troubles digestifs.",
    conseils: "Le repère de l'Anses dépend de la quantité de phytates mangée : 11 mg (homme) et 8 mg (femme) pour une alimentation pauvre en céréales complètes, jusqu'à 14 et 11 mg pour une alimentation qui en est riche. Le trempage, la germination et la fermentation (pain au levain) améliorent l'absorption.",
  },
  vita: {
    resume: "Vitamine de la vision et de la peau, apportée sous deux formes : le rétinol (produits animaux) et le bêta-carotène (végétaux orange et verts).",
    role: "Vision dans la pénombre, renouvellement de la peau et des muqueuses, immunité, croissance et développement de l'embryon.",
    manque: "Rare en France : mauvaise vision nocturne, sécheresse des yeux et de la peau, infections plus fréquentes.",
    exces: "Le rétinol en excès (foie, huiles de foie de poisson, compléments) est toxique : maux de tête, atteintes du foie, fragilité osseuse et malformations du fœtus. Le bêta-carotène des aliments n'est pas toxique.",
    conseils: "Repère : 750 µg pour un homme, 650 µg pour une femme, en équivalents rétinol. Carottes, patate douce, potiron, épinards, abricots apportent du bêta-carotène ; beurre, œufs, fromages du rétinol.",
    grossesse: "Éviter le foie et ses dérivés (pâté, foie gras) et les compléments contenant du rétinol : risque de malformations. Le bêta-carotène des légumes reste recommandé.",
  },
  retinol: {
    resume: "La vitamine A « déjà formée » des produits animaux : foie, beurre, œufs, fromages.",
    exces: "C'est la forme toxique en excès : la limite de sécurité est de 3 000 µg par jour. 100 g de foie peuvent en contenir 10 000 µg ou plus.",
    grossesse: "Le foie et ses produits sont déconseillés pendant toute la grossesse.",
  },
  betacarotene: {
    resume: "Pigment orange des végétaux (carotte, patate douce, potiron, mangue, épinards) que le corps transforme en vitamine A selon ses besoins (environ 6 µg donnent 1 µg de rétinol).",
    exces: "Sans danger par l'alimentation (au pire, la peau prend une teinte orangée). En revanche, les compléments à forte dose augmentent le risque de cancer du poumon chez les fumeurs.",
  },
  vitd: {
    resume: "La vitamine du soleil : la peau la fabrique sous les UVB ; l'alimentation en apporte peu (poissons gras, œufs, produits enrichis).",
    role: "Elle permet l'absorption du calcium et du phosphore, donc la solidité des os ; elle agit aussi sur les muscles et l'immunité.",
    manque: "Très fréquent en France en hiver (environ 80 % de la population a un taux insuffisant). Fragilité osseuse (ostéomalacie, ostéoporose), faiblesse musculaire, chutes chez les personnes âgées ; rachitisme chez l'enfant.",
    exces: "Uniquement par des compléments ou des ampoules mal utilisés (au-delà de 100 µg par jour) : excès de calcium dans le sang, calculs rénaux, troubles cardiaques.",
    conseils: "Repère : 15 µg par jour, difficile à atteindre par l'alimentation seule. Poissons gras (hareng, sardine, maquereau, saumon), jaune d'œuf, produits enrichis ; s'exposer au soleil 15 à 20 minutes par jour bras découverts au printemps et en été. Une supplémentation en hiver se discute avec un médecin.",
    grossesse: "Une ampoule est souvent prescrite au 7e mois.",
  },
  vitd2: { resume: "Forme végétale de la vitamine D (champignons exposés aux UV, levures). Un peu moins efficace que la D3." },
  vitd3: { resume: "Forme animale de la vitamine D, celle que fabrique la peau au soleil ; présente dans les poissons gras et le jaune d'œuf." },
  vite: {
    resume: "Vitamine antioxydante des huiles végétales (tournesol, colza, germe de blé), des oléagineux et des graines.",
    role: "Elle protège les membranes cellulaires et les graisses du corps de l'oxydation.",
    manque: "Rare : troubles neurologiques et musculaires, surtout en cas de mauvaise absorption des graisses.",
    exces: "Uniquement par des compléments (au-delà de 300 mg) : risque de saignement, notamment avec des anticoagulants.",
  },
  alphatoco: { resume: "La forme principale et la plus active de la vitamine E." },
  k1: {
    resume: "Vitamine de la coagulation, présente dans les légumes verts à feuilles (chou, épinards, brocoli, salade) et les herbes.",
    role: "Indispensable à la coagulation du sang ; participe aussi à la solidité des os.",
    manque: "Rare chez l'adulte : saignements, bleus faciles. Le nouveau-né reçoit systématiquement de la vitamine K à la naissance.",
    exces: "Sans danger. En revanche, les personnes sous anticoagulants antivitamine K (AVK) doivent garder un apport régulier en vitamine K, sans à-coups, en accord avec leur médecin.",
  },
  k2: { resume: "Forme de vitamine K fabriquée par des bactéries : fromages affinés, natto, abats. Elle participerait à la fixation du calcium dans les os." },
  vitc: {
    resume: "Vitamine antioxydante des fruits et légumes frais : poivron, agrumes, kiwi, cassis, persil, choux.",
    role: "Elle forme le collagène (peau, vaisseaux, cicatrisation), renforce l'immunité, protège de l'oxydation et multiplie l'absorption du fer végétal.",
    manque: "Fatigue, gencives qui saignent, cicatrisation lente, infections ; le scorbut en cas de carence sévère (rare).",
    exces: "Sans danger par l'alimentation. Au-delà de 1 g par jour en compléments : troubles digestifs, calculs rénaux chez les personnes prédisposées.",
    conseils: "Repère : 110 mg par jour. Elle est fragile (chaleur, air, eau de cuisson) : privilégier les fruits et légumes crus ou cuits peu de temps à la vapeur. Un kiwi ou une orange couvre la majeure partie du besoin.",
  },
  b1: {
    resume: "Vitamine de la transformation des glucides en énergie : porc, céréales complètes, légumineuses, levure.",
    role: "Elle sert à produire de l'énergie à partir des glucides et au fonctionnement des nerfs et du cœur.",
    manque: "Fatigue, irritabilité, troubles de la mémoire, atteinte des nerfs ; le béribéri ou l'encéphalopathie de Wernicke dans les cas graves, surtout en cas d'alcoolisme.",
    exces: "Sans danger connu par l'alimentation.",
  },
  b2: {
    resume: "Vitamine de la production d'énergie : laitages, œufs, abats, viandes, amandes.",
    role: "Elle participe à la production d'énergie, à la santé de la peau, des yeux et des muqueuses et à l'activation d'autres vitamines B.",
    manque: "Rare : lèvres gercées, fissures aux coins de la bouche, langue rouge, yeux sensibles à la lumière.",
    exces: "Sans danger connu : le surplus est éliminé dans les urines (qui deviennent jaune vif).",
  },
  b3: {
    resume: "Vitamine de la production d'énergie : viandes, poissons, cacahuètes, céréales complètes. Le corps en fabrique aussi à partir du tryptophane.",
    role: "Production d'énergie, santé de la peau, des nerfs et du système digestif.",
    manque: "Rare en France : la pellagre (peau, diarrhées, troubles mentaux).",
    exces: "Uniquement par des compléments : l'acide nicotinique provoque des bouffées de chaleur dès 10 mg, et des atteintes du foie à forte dose.",
  },
  b5: {
    resume: "Vitamine présente dans presque tous les aliments, surtout abats, œufs, champignons, céréales complètes.",
    role: "Elle intervient dans la production d'énergie et la fabrication des graisses, des hormones et de neurotransmetteurs.",
    manque: "Quasi inexistant.",
    exces: "Sans danger connu.",
  },
  b6: {
    resume: "Vitamine des protéines : volailles, poissons, pommes de terre, bananes, légumineuses, oléagineux.",
    role: "Utilisation des protéines, fabrication de neurotransmetteurs (sérotonine, dopamine), formation des globules rouges, immunité.",
    manque: "Peu fréquent : anémie, irritabilité, lésions de la bouche, baisse de l'immunité.",
    exces: "Uniquement par des compléments : au-delà de 12 mg par jour (limite EFSA 2023), atteinte des nerfs (fourmillements, perte de sensibilité), réversible à l'arrêt. Attention au cumul de compléments.",
  },
  b9: {
    resume: "Les folates, vitamine des « feuilles » : légumes verts, légumineuses, abats, levure, fromages affinés.",
    role: "Indispensables à la fabrication de l'ADN et à la division cellulaire : globules rouges, renouvellement des tissus et surtout développement de l'embryon (fermeture du tube neural).",
    manque: "Anémie, fatigue, lésions de la bouche. En début de grossesse, un manque augmente le risque de malformations graves du tube neural (spina bifida).",
    exces: "Pas de risque avec les folates des aliments. L'acide folique des compléments et produits enrichis est limité à 1 000 µg par jour : au-delà, il peut masquer une carence en vitamine B12.",
    conseils: "Repère : 330 µg par jour. Légumes verts (épinards, mâche, cresson, brocoli, asperges), légumineuses (lentilles, pois chiches), agrumes. Les folates sont fragiles à la chaleur : légumes crus ou cuits peu de temps.",
    grossesse: "Repère porté à 600 µg. Une supplémentation en acide folique (400 µg par jour) est recommandée dès le projet de grossesse, au moins 4 semaines avant la conception et jusqu'à 12 semaines de grossesse.",
  },
  acidefolique: { resume: "Forme synthétique de la vitamine B9, ajoutée aux compléments et à certains aliments enrichis (céréales du petit-déjeuner). Mieux absorbée que les folates naturels ; limite de sécurité : 1 000 µg par jour." },
  b12: {
    resume: "Vitamine présente uniquement dans les produits animaux : abats, fruits de mer, poissons, viandes, œufs, laitages.",
    role: "Formation des globules rouges, fonctionnement du système nerveux, fabrication de l'ADN.",
    manque: "Anémie, fatigue, puis troubles neurologiques (fourmillements, troubles de la mémoire, de l'équilibre) parfois irréversibles. Concerne les végétaliens sans complément, les personnes âgées (moins bonne absorption) et certains traitements (metformine, anti-acides).",
    exces: "Sans danger connu.",
    conseils: "Repère : 4 µg par jour. Indispensable de se supplémenter en cas d'alimentation végétalienne : les algues et la spiruline n'en apportent pas sous une forme utilisable.",
    grossesse: "Repère porté à 4,5 µg. Un manque chez la mère expose le bébé à des troubles du développement.",
  },
};

// Fiches des acides aminés (server/assimilation.js).
Object.assign(module.exports, require('./assimilation').AA_FICHES);
